formatter: "markdown table"

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: false
  default: true
  description: true
  escape: false
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

output:
  file: README.md
  mode: inject
